name: Docker

on:
  push:
    branches:
      - main

jobs:
  weekend_offline_task:
    runs-on: ubuntu-latest
    name: Weekend offline task
    steps:
      - name: Prepare image
        uses: docker://matich/weekend_offline_task:prepared
        
      - name: Clone repository
        run: |
          git clone https://github.com/biopython/biopython
      - name: Build biopython
        run: |
           cd biopython >> $GITHUB_ENV
           python3 setup.py build
      - name: Test biopython
        run: |
           cd biopython >> $GITHUB_ENV
           python3 setup.py test --offline >> $GITHUB_ENV
#         with:
#            - name: Clone repository
#              run: |
#                git clone https://github.com/biopython/biopython
#            - name: Build biopython
#              run: |
#               cd biopython >> $GITHUB_ENV
#               python3.9 setup.py build
#            - name: Test biopython
#              run: |
#               cd biopython >> $GITHUB_ENV
#               python3.9 setup.py test --offline >> $GITHUB_ENV

#         # uses: chermath/dockerbiopython@v1
      
