name: Docker

on:
  push:
    branches:
      - main

jobs:
  weekend_offline_task:
    runs-on: ubuntu-latest
    
    name: Weekend offline task
    steps:
      -
        name: Docker login
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}'
        run: |
          docker login -u $username -p $password
      -
        name: Get docker container
        run: |
          docker pull matich/weekend_offline_task:prepared_with_dev
      - 
        name: Clone repository
        run: |
          git clone https://github.com/biopython/biopython
      - 
        name: Build biopython
        run: |
           cd biopython
           python3.9 setup.py build
      - 
        name: Test biopython
        run: |
           cd biopython
           python3.9 setup.py test --offline
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: matich/weekend_offline_task:latest
#         with:
#            - name: Clone repository
#              run: |
#                git clone https://github.com/biopython/biopython
#            - name: Build biopython
#              run: |
#               cd biopython >> $GITHUB_ENV
#               python3.9 setup.py build
#            - name: Test biopython
#              run: |
#               cd biopython >> $GITHUB_ENV
#               python3.9 setup.py test --offline >> $GITHUB_ENV

#         # uses: chermath/dockerbiopython@v1
      
