name: Docker

on:
  push:
    branches:
      - main

jobs:
  weekend_offline_task:
    runs-on: ubuntu-latest
    
    name: Weekend offline task
    steps:
      -
        name: Docker login
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $username -p $password
      -
        name: Get docker container
        run: |
          docker pull matich/weekend_offline_task:prepared_with_dev
      - 
        name: Run container
        run: |
          docker run matich/weekend_offline_task:prepared_with_dev
      -
        name: Build container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: matich/weekend_offline_task:biopython
      -
       name: Docker hub push
       run: |
          docker push matich/weekend_offline_task:biopython
