name: Docker

on:
  push:
    branches:
      - main

jobs:
  weekend_offline_task:
    runs-on: ubuntu-latest
    
    name: weekend offline task
    steps:
      -
        name: docker login
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $username -p $password
      -
        name: get docker container
        run: |
          docker pull matich/weekend_offline_task:prepared_tests
      - 
        name: run container
        run: |
          docker run matich/weekend_offline_task:prepared_tests
      -
        name: build container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: matich/weekend_offline_task:biopython
      -
       name: docker hub push
       run: |
          docker push matich/weekend_offline_task:biopython
