name: Docker

on:
  push:
    branches:
      - main

jobs:
  weekend_offline_task:
    runs-on: chermath/dockerbiopython@v1
    name: Weekend offline task
    steps:
#       - name: Prepare image
#         id: hello
#         uses: chermath/dockerbiopython@v1
      - name: Clone repository
        run: |
          git clone https://github.com/biopython/biopython
      - name: Build biopython
        run: |
           cd biopython >> $GITHUB_ENV
           python3 setup.py build
      - name: Test biopython
        run: |
           cd biopython >> $GITHUB_ENV
           python3 setup.py test --offline >> $GITHUB_ENV
